-- Create Table
CREATE TABLE "notes" (
    "id"        INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "content"   TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
